---
- name: Create directory for tools
  become: true
  file:
    path: /opt/offsec_tools
    state: directory
    mode: '0755'

- name: Download Responder repository from GitHub
  become: true
  git:
    repo: https://github.com/lgandx/Responder.git
    dest: /opt/offsec_tools/Responder
    version: master
    force: yes

- name: Download AzSubEnum repository from GitHub
  become: true
  git:
    repo: https://github.com/yuyudhn/AzSubEnum
    dest: /opt/offsec_tools/AzSubEnum
    version: main
    force: yes

- name: Download Omnispray repository from GitHub
  become: true
  git:
    repo: https://github.com/0xZDH/Omnispray
    dest: /home/azureuser/offsec_tools/Omnispray
    version: master
    force: yes

- name: Download Evilginx2 repository from GitHub
  become: true
  git:
    repo: https://github.com/kgretzky/evilginx2
    dest: /home/azureuser/offsec_tools/evilginx2
    version: master
    force: yes
