---
- name: Install and configure Fail2Ban
  hosts: all
  become: yes

  tasks:
    - name: Ensure Fail2Ban is installed
      apt:
        name: fail2ban
        state: present

    - name: Ensure Fail2Ban service is enabled and running
      service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Configure Fail2Ban
      copy:
        src: jail.local
        dest: /etc/fail2ban/jail.local
        mode: "0644"
        backup: yes

    - name: Restart Fail2Ban service to apply configuration changes
      service:
        name: fail2ban
        state: restarted

  handlers:
    - name: Restart Fail2Ban
      service:
        name: fail2ban
        state: restarted
